language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t 592115001/htmltest .
- docker push 592115001/htmltest
after_success:
- docker stop htmltest
- docker rm htmltest
- docker run -p 8088:80 -d 592115001/htmltest:latest
service: docker
env:
  global:
    secure: vWy3m+hdCwu3frfW8Ynsi1AzhOFdtXl88fYeRPpAtlN2ch/ro7Jv5Ag9brQjIamWgg0H++9yWIlZ86dVULYDeHLgsgx4+6gtKoLm8bw+BMHexnpTzafpdc3FUC4mNsJSIuq5Ezb4Vu3xPzRRK2Ff/vO5FBrK+bFqoSpLPRWQ9Xzh3lOi/kmqHMYdnbQ7UKRNR/TEG6sJB91mg8WW1HCjr8Fj2KuP7DdnbVRyF1E8YYSAwbZ9jwJZT6rpvDymXzwmszUDOuF7doOrXqGaRiyih1JvpEqC0y63wSCEVQHV2x+fDyDjwJnBi8QQE2zXASq6eLLSLk2ky95ofSNTnfBMoWf1rmnhe9XqNwhPE+wuAeiKu6mMZAHSVgXkq9rolQGtlfn0MsUU/sIaAVarJCPU1RyqJNhWntKC7WsJEygcNi4Q4BeEWadxNFOL34QXRDyEJQqCxBjeBk3r3vItQLFpEdtU6LerJvy5ftx5T3oLrx1ee4TANXPbgxws7c4BJAsWfxM4ZqF0BucB/NrFoZes+HfTY8IDKfcKkrdHEkwgy/dKnZJttWqThi1XU6MnfwvxFV3zS6EHWlkHJZUg0q/O3hmzC5QS5pJ7OTRol+nDc1oks1oOS+FUbVkexsbxA+tjRXr8/RInxjph2KS9TUP3fLQNmX8mFzWLDdTnOrR3uTU=
dd:
  secure: BX2OtPlYbIWGokl8hqRd/NRXsDrOfNTR0nRLeZNycFT03h4NRtyzmQM10Eqsbr+U7Lq4LWdOUtn0uIkWU6X6iGFSMT8SwiTc23QsJZkh/CijzJQSLp++tcXn6Fbr7iqYKkDBADEI94FGt268AgHk37/R7T6DpLxZLFbev3Vo1HfZkrkkO5AMR3t++gmi17F1dzsrBcmf0L2Tf24tYOrLXP0iLQ/ZNTf9dF9f/+j90UQEzZQ26p1IxnCDJ7lyGH5krWpRsDQgEjYtHnddIm5NA1zTpnFfYYdsz9Mqo2qDBsTmzXuxMz/DtQKMr7HNytSkEcvr7yLEFB7YysMBfTOBx35va6pKZ01BugqUdZEzkM+cqT3KfRPP25qTa/39hXuvsejaDGCyYbCA8AA4bW1xBpQgqvK/TvcmoUrXC+FqDrqqQvpd1N04wsRp0I8yWJTzZ9uUaD/10ijse94sFWIbz2m0hcybtURrADNN8WmtpqC3pz+XkZZo2w08r8NTaqygkrTf5bMG8a9rYB29zLpfYu+45jPXPguzBpPLFgfC6wDINobVr3I9vumV4Zm1cmttnAPPbz5O3GBIfoVfWW3AKkJcVGd15xVKXJGKrMlIuV/JXDYDqcygGjsOaJ/Ruy08UMzPQdwXMhkzPCbM8rf82n2ZRbanTGDsviN7p8es4yM=
